//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterModule.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MasterModule.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abre contratos S/N.
        /// </summary>
        internal static string AbreContratosSN {
            get {
                return ResourceManager.GetString("AbreContratosSN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admite Recogida fuera de base.
        /// </summary>
        internal static string AdmiteRecogidaFueraDeBase {
            get {
                return ResourceManager.GetString("AdmiteRecogidaFueraDeBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admite Reserva ON Line.
        /// </summary>
        internal static string AdmiteReservaONLine {
            get {
                return ResourceManager.GetString("AdmiteReservaONLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canon Fijo Mes: .
        /// </summary>
        internal static string CanonFijoMes {
            get {
                return ResourceManager.GetString("CanonFijoMes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carga...
        /// </summary>
        internal static string Carga {
            get {
                return ResourceManager.GetString("Carga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codigo Sociedad.
        /// </summary>
        internal static string CodigoSociedad {
            get {
                return ResourceManager.GetString("CodigoSociedad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacto.
        /// </summary>
        internal static string Contacto {
            get {
                return ResourceManager.GetString("Contacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña WS:.
        /// </summary>
        internal static string ContraseñaWS {
            get {
                return ResourceManager.GetString("ContraseñaWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CP.
        /// </summary>
        internal static string CP {
            get {
                return ResourceManager.GetString("CP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credenciales Web.
        /// </summary>
        internal static string CredencialesWeb {
            get {
                return ResourceManager.GetString("CredencialesWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cta.Soportado.
        /// </summary>
        internal static string CtaSoportado {
            get {
                return ResourceManager.GetString("CtaSoportado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuenta C/P.
        /// </summary>
        internal static string CuentaCP {
            get {
                return ResourceManager.GetString("CuentaCP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuenta L/P.
        /// </summary>
        internal static string CuentaLP {
            get {
                return ResourceManager.GetString("CuentaLP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos Empresa.
        /// </summary>
        internal static string DatosEmpresa {
            get {
                return ResourceManager.GetString("DatosEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devolución fuera de Horas: .
        /// </summary>
        internal static string DevoluciónFueraDeHoras {
            get {
                return ResourceManager.GetString("DevoluciónFueraDeHoras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dirección.
        /// </summary>
        internal static string Dirección {
            get {
                return ResourceManager.GetString("Dirección", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segunda Dirección.
        /// </summary>
        internal static string Dirección2 {
            get {
                return ResourceManager.GetString("Dirección2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DTO Máximo .
        /// </summary>
        internal static string DTOMáximo {
            get {
                return ResourceManager.GetString("DTOMáximo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email. Confirmed Res.: .
        /// </summary>
        internal static string EmailConfirmedRes {
            get {
                return ResourceManager.GetString("EmailConfirmedRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email. On-Request Res.:.
        /// </summary>
        internal static string EmailOnRequestRes {
            get {
                return ResourceManager.GetString("EmailOnRequestRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email. Rejected Res.: .
        /// </summary>
        internal static string EmailRejectedRes {
            get {
                return ResourceManager.GetString("EmailRejectedRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emite y Paga Clientes.
        /// </summary>
        internal static string EmiteYPagaClientes {
            get {
                return ResourceManager.GetString("EmiteYPagaClientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empresa.
        /// </summary>
        internal static string Empresa {
            get {
                return ResourceManager.GetString("Empresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrega fuera de Horas: .
        /// </summary>
        internal static string EntregaFueraDeHoras {
            get {
                return ResourceManager.GetString("EntregaFueraDeHoras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es Aeropuerto S/N .
        /// </summary>
        internal static string EsAeropuertoSN {
            get {
                return ResourceManager.GetString("EsAeropuertoSN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es Intracomunitario.
        /// </summary>
        internal static string EsIntracomunitario {
            get {
                return ResourceManager.GetString("EsIntracomunitario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estación de tren .
        /// </summary>
        internal static string EstaciónDeTren {
            get {
                return ResourceManager.GetString("EstaciónDeTren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        internal static string Fax {
            get {
                return ResourceManager.GetString("Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de Alta.
        /// </summary>
        internal static string FechaDeAlta {
            get {
                return ResourceManager.GetString("FechaDeAlta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de Baja.
        /// </summary>
        internal static string FechaDeBaja {
            get {
                return ResourceManager.GetString("FechaDeBaja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Fabricacion.
        /// </summary>
        internal static string FechaFabricacion {
            get {
                return ResourceManager.GetString("FechaFabricacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Matriculacion.
        /// </summary>
        internal static string FechaMatriculacion {
            get {
                return ResourceManager.GetString("FechaMatriculacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Festividad.
        /// </summary>
        internal static string Festividad {
            get {
                return ResourceManager.GetString("Festividad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Festivos.
        /// </summary>
        internal static string Festivos {
            get {
                return ResourceManager.GetString("Festivos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forma de Pago.
        /// </summary>
        internal static string FormaDePago {
            get {
                return ResourceManager.GetString("FormaDePago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestión de albaranes.
        /// </summary>
        internal static string GestiónDeAlbaranes {
            get {
                return ResourceManager.GetString("GestiónDeAlbaranes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestion Festividades.
        /// </summary>
        internal static string GestionFestividades {
            get {
                return ResourceManager.GetString("GestionFestividades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehiculos.
        /// </summary>
        internal static string Header_Vehiculos {
            get {
                return ResourceManager.GetString("Header_Vehiculos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horario Desde.
        /// </summary>
        internal static string HorarioDesde {
            get {
                return ResourceManager.GetString("HorarioDesde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID. Cliente.
        /// </summary>
        internal static string IDCliente {
            get {
                return ResourceManager.GetString("IDCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.Contrato SAVIA: .
        /// </summary>
        internal static string IDContratoSAVIA {
            get {
                return ResourceManager.GetString("IDContratoSAVIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.Local SAVIA: .
        /// </summary>
        internal static string IDLocalSAVIA {
            get {
                return ResourceManager.GetString("IDLocalSAVIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Móvil.
        /// </summary>
        internal static string Móvil {
            get {
                return ResourceManager.GetString("Móvil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewSupplier.
        /// </summary>
        internal static string NewSupplier {
            get {
                return ResourceManager.GetString("NewSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NIF.
        /// </summary>
        internal static string NIF {
            get {
                return ResourceManager.GetString("NIF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No definido.
        /// </summary>
        internal static string NoDefinido {
            get {
                return ResourceManager.GetString("NoDefinido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        internal static string Nombre {
            get {
                return ResourceManager.GetString("Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre Commercial.
        /// </summary>
        internal static string NombreCommercial {
            get {
                return ResourceManager.GetString("NombreCommercial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No &apos;On-Request&apos; .
        /// </summary>
        internal static string NoOnRequest {
            get {
                return ResourceManager.GetString("NoOnRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notas.
        /// </summary>
        internal static string Notas {
            get {
                return ResourceManager.GetString("Notas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numero.
        /// </summary>
        internal static string Numero {
            get {
                return ResourceManager.GetString("Numero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observaciones.
        /// </summary>
        internal static string Observaciones {
            get {
                return ResourceManager.GetString("Observaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oficina.
        /// </summary>
        internal static string Oficina {
            get {
                return ResourceManager.GetString("Oficina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ofi. Flota .
        /// </summary>
        internal static string OfiFlota {
            get {
                return ResourceManager.GetString("OfiFlota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On way nacional, On request .
        /// </summary>
        internal static string OnWayNacionalOnRequest {
            get {
                return ResourceManager.GetString("OnWayNacionalOnRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Via.
        /// </summary>
        internal static string OrderCommunicationWay_Via {
            get {
                return ResourceManager.GetString("OrderCommunicationWay_Via", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to País.
        /// </summary>
        internal static string Pais {
            get {
                return ResourceManager.GetString("Pais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Web.
        /// </summary>
        internal static string PasswordWeb {
            get {
                return ResourceManager.GetString("PasswordWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plazo de pago.
        /// </summary>
        internal static string PlazoDePago {
            get {
                return ResourceManager.GetString("PlazoDePago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Población.
        /// </summary>
        internal static string Población {
            get {
                return ResourceManager.GetString("Población", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poliza assistencia addicional.
        /// </summary>
        internal static string PolizaAssistenciaAddicional {
            get {
                return ResourceManager.GetString("PolizaAssistenciaAddicional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pon hora de ida.
        /// </summary>
        internal static string PonHoraDeIda {
            get {
                return ResourceManager.GetString("PonHoraDeIda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pon hora de vuelta.
        /// </summary>
        internal static string PonHoraDeVuelta {
            get {
                return ResourceManager.GetString("PonHoraDeVuelta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefijo.
        /// </summary>
        internal static string Prefijo {
            get {
                return ResourceManager.GetString("Prefijo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provincia.
        /// </summary>
        internal static string Provincia {
            get {
                return ResourceManager.GetString("Provincia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recogida en Festivo NO &apos;On-Request&apos; &quot; .
        /// </summary>
        internal static string RecogidaEnFestivoNOOnRequest {
            get {
                return ResourceManager.GetString("RecogidaEnFestivoNOOnRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seguro.
        /// </summary>
        internal static string Seguro {
            get {
                return ResourceManager.GetString("Seguro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Bookings by Mail.
        /// </summary>
        internal static string SendBookingsByMail {
            get {
                return ResourceManager.GetString("SendBookingsByMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siempre On request .
        /// </summary>
        internal static string SiempreOnRequest {
            get {
                return ResourceManager.GetString("SiempreOnRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sin Coste .
        /// </summary>
        internal static string SinCoste {
            get {
                return ResourceManager.GetString("SinCoste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clave.Ppto.
        /// </summary>
        internal static string StringConstants_ClavePpto {
            get {
                return ResourceManager.GetString("StringConstants_ClavePpto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha compra.
        /// </summary>
        internal static string StringConstants_FechaCompra {
            get {
                return ResourceManager.GetString("StringConstants_FechaCompra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observation.
        /// </summary>
        internal static string StringConstants_Observation {
            get {
                return ResourceManager.GetString("StringConstants_Observation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teléfono.
        /// </summary>
        internal static string Teléfono {
            get {
                return ResourceManager.GetString("Teléfono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporada Apertura.
        /// </summary>
        internal static string TemporadaApertura {
            get {
                return ResourceManager.GetString("TemporadaApertura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo IVA Web.
        /// </summary>
        internal static string TipoIVAWeb {
            get {
                return ResourceManager.GetString("TipoIVAWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo Prov..
        /// </summary>
        internal static string TipoProv {
            get {
                return ResourceManager.GetString("TipoProv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario Web.
        /// </summary>
        internal static string UsuarioWeb {
            get {
                return ResourceManager.GetString("UsuarioWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario WS:.
        /// </summary>
        internal static string UsuarioWS {
            get {
                return ResourceManager.GetString("UsuarioWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web.
        /// </summary>
        internal static string Web {
            get {
                return ResourceManager.GetString("Web", resourceCulture);
            }
        }
    }
}
