Public Class ThemeDefault
    Inherits Theme_Definicion

    Sub New()

        Iconos.Add(ThemeDefault.euIconos.Clientes_Ic, My.Resources.Clientes_Def)
        Iconos.Add(ThemeDefault.euIconos.Proveedores_Ic, My.Resources.Proveedor_Def)
        Iconos.Add(ThemeDefault.euIconos.Facturas_Ic, My.Resources.Facturas_Def)
        Iconos.Add(ThemeDefault.euIconos.Contratos_Ic, My.Resources.Contratos_IC_Def)
        Iconos.Add(ThemeDefault.euIconos.Config_Ic, My.Resources.Config_Def)
        Iconos.Add(ThemeDefault.euIconos.Add_Ic, My.Resources.Add_Def)
        Iconos.Add(ThemeDefault.euIconos.Save_Ic, My.Resources.SaveAs_Def)
        Iconos.Add(ThemeDefault.euIconos.Refresh_Ic, My.Resources.Refresh_Def)
        Iconos.Add(ThemeDefault.euIconos.Delete_Ic, My.Resources.Delete_Def)
        Iconos.Add(ThemeDefault.euIconos.Start_Ic, My.Resources.Start_Def)
        Iconos.Add(ThemeDefault.euIconos.Previus_Ic, My.Resources.Previus_Def)
        Iconos.Add(ThemeDefault.euIconos.Next_Ic, My.Resources.Next_Def)
        Iconos.Add(ThemeDefault.euIconos.End_Ic, My.Resources.End_Def)
        Iconos.Add(ThemeDefault.euIconos.Aceptar_Ic, My.Resources.Check_Def)
        Iconos.Add(ThemeDefault.euIconos.Cancelar_Ic, My.Resources.U_Check_Def)
        Iconos.Add(ThemeDefault.euIconos.Buscar_Ic, My.Resources.Search_Def)
        Iconos.Add(ThemeDefault.euIconos.Print_Ic, My.Resources.Print_Def)
        Iconos.Add(ThemeDefault.euIconos.Export_Ic, My.Resources.Export_Def)
        Iconos.Add(ThemeDefault.euIconos.Mail_Ic, My.Resources.Mail_Def)
        Iconos.Add(ThemeDefault.euIconos.Pegar_Ic, My.Resources.Paste_Def)
        Iconos.Add(ThemeDefault.euIconos.Copiar_Ic, My.Resources.Copy_Def)
        Iconos.Add(ThemeDefault.euIconos.Cortar_Ic, My.Resources.Cut_Def)
        Iconos.Add(ThemeDefault.euIconos.MSWord, My.Resources.MSWord_Def)
        Iconos.Add(ThemeDefault.euIconos.HTML_File, My.Resources.HTML_File_Def)
        Iconos.Add(ThemeDefault.euIconos.TXT_File, My.Resources.TXT_File_Def)
        Iconos.Add(ThemeDefault.euIconos.Image, My.Resources.InsertImage_Def)
        Iconos.Add(ThemeDefault.euIconos.AddLink, My.Resources.InsertLink_Def)
        Iconos.Add(ThemeDefault.euIconos.InsertTable, My.Resources.InsertTable_Def)
        Iconos.Add(ThemeDefault.euIconos.CerrarCtr, My.Resources.CerrarCtr_Def)
        Iconos.Add(ThemeDefault.euIconos.VerCtr, My.Resources.VerCtr_Def)
        Iconos.Add(ThemeDefault.euIconos.ReabrirCtr, My.Resources.ReabrirCtr_Def)
        Iconos.Add(ThemeDefault.euIconos.ProlongarCtr, My.Resources.ProlongarCtr_Def)
        Iconos.Add(ThemeDefault.euIconos.Facturar, My.Resources.Facturar_Def)
        Iconos.Add(ThemeDefault.euIconos.Cobros, My.Resources.Cobros_Def)
        Iconos.Add(ThemeDefault.euIconos.AddCtr, My.Resources.AddCtr_Def)
        Iconos.Add(ThemeDefault.euIconos.Reservas_Ic, My.Resources.Reserva_Def)

        IconosTree.Add(ThemeDefault.euIconosTree.Auxiliares_Ict, My.Resources.User16_Def)
        IconosTree.Add(ThemeDefault.euIconosTree.Auxiliares_Car, My.Resources.Car16_Def)
        IconosTree.Add(ThemeDefault.euIconosTree.Check_Ict, My.Resources.Check16_Def)
        IconosTree.Add(ThemeDefault.euIconosTree.UnCheck_Ict, My.Resources.U_Check16_Def)

        'IconosMini.Add(ThemeDefault.euIconosMini.Buscar_Ic, My.Resources.Buscar_mini_Def)
        IconosMini.Add(ThemeDefault.euIconosMini.Buscar_Ic, My.Resources.Search16_Def)
        IconosMini.Add(ThemeDefault.euIconosMini.Lupa_Ic, My.Resources.Lupa_mini_Def)
        IconosMini.Add(ThemeDefault.euIconosMini.Actualizar_Ic, My.Resources.Actualizar_mini_Def)
        IconosMini.Add(ThemeDefault.euIconosMini.Mail_Ic, My.Resources.Mail_mini_Def)
        IconosMini.Add(ThemeDefault.euIconosMini.Pegar_Ic, My.Resources.Paste_mini_Def)
        IconosMini.Add(ThemeDefault.euIconosMini.Copiar_Ic, My.Resources.Copy_mini_Def)
        IconosMini.Add(ThemeDefault.euIconosMini.Cortar_Ic, My.Resources.Cut_mini_Def)
        IconosMini.Add(ThemeDefault.euIconosMini.Bold_Ic, My.Resources.Bold_mini_Def)
        IconosMini.Add(ThemeDefault.euIconosMini.Italic_Ic, My.Resources.Italic_mini_Def)
        IconosMini.Add(ThemeDefault.euIconosMini.Underline_Ic, My.Resources.Underline_mini_Def)
        IconosMini.Add(ThemeDefault.euIconosMini.Color_Ic, My.Resources.Color16_Def)
        IconosMini.Add(ThemeDefault.euIconosMini.Del_Ic, My.Resources.Del16_Def)



        IconosMini.Add(ThemeDefault.euIconosMini.AlinearIzquierda, My.Resources.AlignLeft_mini_Def)
        IconosMini.Add(ThemeDefault.euIconosMini.AlinearDerecha, My.Resources.AlignRight_mini_Def)
        IconosMini.Add(ThemeDefault.euIconosMini.AlinearJustificar, My.Resources.AlignJustify_mini_Def)
        IconosMini.Add(ThemeDefault.euIconosMini.AlinearCentrar, My.Resources.AlignCenter_mini_Def)

        IconosMini.Add(ThemeDefault.euIconosMini.AumentarFuente, My.Resources.IncreaseFont_mini_Def)
        IconosMini.Add(ThemeDefault.euIconosMini.DisminuirFuente, My.Resources.DecreaseFont_mini_Def)
        IconosMini.Add(ThemeDefault.euIconosMini.ColorFuente, My.Resources.TextColor_mini_Def)
        IconosMini.Add(ThemeDefault.euIconosMini.ColorSubrayado, My.Resources.ChiselMarker_mini_Def)
    End Sub

End Class
