//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotoFrameControl.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PhotoFrameControl.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Añade una nueva imagen...
        /// </summary>
        internal static string PhotoFrame_ImageButton_Click_AñadeUnaNuevaImagen {
            get {
                return ResourceManager.GetString("PhotoFrame_ImageButton_Click_AñadeUnaNuevaImagen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fichero Imagen.
        /// </summary>
        internal static string PhotoFrame_ImageButton_Click_ImageFiles {
            get {
                return ResourceManager.GetString("PhotoFrame_ImageButton_Click_ImageFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motivacion: .
        /// </summary>
        internal static string PhotoFrame_ImageButton_Click_Motivacion {
            get {
                return ResourceManager.GetString("PhotoFrame_ImageButton_Click_Motivacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede abrir el fichero:.
        /// </summary>
        internal static string PhotoFrame_ImageButton_Click_NoSePuedeAbrirElFichero {
            get {
                return ResourceManager.GetString("PhotoFrame_ImageButton_Click_NoSePuedeAbrirElFichero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foto.
        /// </summary>
        internal static string PhotoFrame_PhotoName_Foto {
            get {
                return ResourceManager.GetString("PhotoFrame_PhotoName_Foto", resourceCulture);
            }
        }
    }
}
