//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterModule.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MasterModule.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestión de albaranes.
        /// </summary>
        internal static string ProviderConstants_GestiónDeAlbaranes {
            get {
                return ResourceManager.GetString("ProviderConstants_GestiónDeAlbaranes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacto.
        /// </summary>
        internal static string ProviderInfoViewModel_Contacto {
            get {
                return ResourceManager.GetString("ProviderInfoViewModel_Contacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segunda Dirección.
        /// </summary>
        internal static string ProviderInfoViewModel_Dirección2 {
            get {
                return ResourceManager.GetString("ProviderInfoViewModel_Dirección2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string ProviderInfoViewModel_Email {
            get {
                return ResourceManager.GetString("ProviderInfoViewModel_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empresa.
        /// </summary>
        internal static string ProviderInfoViewModel_Empresa {
            get {
                return ResourceManager.GetString("ProviderInfoViewModel_Empresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        internal static string ProviderInfoViewModel_Fax {
            get {
                return ResourceManager.GetString("ProviderInfoViewModel_Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de Alta.
        /// </summary>
        internal static string ProviderInfoViewModel_FechaDeAlta {
            get {
                return ResourceManager.GetString("ProviderInfoViewModel_FechaDeAlta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de Baja.
        /// </summary>
        internal static string ProviderInfoViewModel_FechaDeBaja {
            get {
                return ResourceManager.GetString("ProviderInfoViewModel_FechaDeBaja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuenta C/P.
        /// </summary>
        internal static string ProviderInfoViewModel_LoadAccountLeft_CuentaCP {
            get {
                return ResourceManager.GetString("ProviderInfoViewModel_LoadAccountLeft_CuentaCP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plazo de pago.
        /// </summary>
        internal static string ProviderInfoViewModel_LoadAccountLeft_PlazoDePago {
            get {
                return ResourceManager.GetString("ProviderInfoViewModel_LoadAccountLeft_PlazoDePago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CP.
        /// </summary>
        internal static string ProviderInfoViewModel_LoadLeftPart_CP {
            get {
                return ResourceManager.GetString("ProviderInfoViewModel_LoadLeftPart_CP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dirección.
        /// </summary>
        internal static string ProviderInfoViewModel_LoadLeftPart_Dirección {
            get {
                return ResourceManager.GetString("ProviderInfoViewModel_LoadLeftPart_Dirección", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to País.
        /// </summary>
        internal static string ProviderInfoViewModel_LoadLeftPart_Pais {
            get {
                return ResourceManager.GetString("ProviderInfoViewModel_LoadLeftPart_Pais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provincia.
        /// </summary>
        internal static string ProviderInfoViewModel_LoadLeftPart_Provincia {
            get {
                return ResourceManager.GetString("ProviderInfoViewModel_LoadLeftPart_Provincia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefono.
        /// </summary>
        internal static string ProviderInfoViewModel_LoadLeftPart_Telefono {
            get {
                return ResourceManager.GetString("ProviderInfoViewModel_LoadLeftPart_Telefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Móvil.
        /// </summary>
        internal static string ProviderInfoViewModel_Móvil {
            get {
                return ResourceManager.GetString("ProviderInfoViewModel_Móvil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NIF.
        /// </summary>
        internal static string ProviderInfoViewModel_NIF {
            get {
                return ResourceManager.GetString("ProviderInfoViewModel_NIF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        internal static string ProviderInfoViewModel_Nombre {
            get {
                return ResourceManager.GetString("ProviderInfoViewModel_Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre Commercial.
        /// </summary>
        internal static string ProviderInfoViewModel_NombreCommercial {
            get {
                return ResourceManager.GetString("ProviderInfoViewModel_NombreCommercial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notas.
        /// </summary>
        internal static string ProviderInfoViewModel_Notas {
            get {
                return ResourceManager.GetString("ProviderInfoViewModel_Notas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numero.
        /// </summary>
        internal static string ProviderInfoViewModel_Numero {
            get {
                return ResourceManager.GetString("ProviderInfoViewModel_Numero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observaciones.
        /// </summary>
        internal static string ProviderInfoViewModel_Observaciones {
            get {
                return ResourceManager.GetString("ProviderInfoViewModel_Observaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oficina.
        /// </summary>
        internal static string ProviderInfoViewModel_Oficina {
            get {
                return ResourceManager.GetString("ProviderInfoViewModel_Oficina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Población.
        /// </summary>
        internal static string ProviderInfoViewModel_Población {
            get {
                return ResourceManager.GetString("ProviderInfoViewModel_Población", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teléfono.
        /// </summary>
        internal static string ProviderInfoViewModel_Teléfono {
            get {
                return ResourceManager.GetString("ProviderInfoViewModel_Teléfono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo Prov..
        /// </summary>
        internal static string ProviderInfoViewModel_TipoProv {
            get {
                return ResourceManager.GetString("ProviderInfoViewModel_TipoProv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web.
        /// </summary>
        internal static string ProviderInfoViewModel_Web {
            get {
                return ResourceManager.GetString("ProviderInfoViewModel_Web", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROVEE1.
        /// </summary>
        internal static string ProviderModule_Table1 {
            get {
                return ResourceManager.GetString("ProviderModule_Table1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROVEE2.
        /// </summary>
        internal static string ProviderModule_Table2 {
            get {
                return ResourceManager.GetString("ProviderModule_Table2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewSupplier.
        /// </summary>
        internal static string ProvidersControlViewModel_OpenNewItem_NewSupplier {
            get {
                return ResourceManager.GetString("ProvidersControlViewModel_OpenNewItem_NewSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Via.
        /// </summary>
        internal static string UiDirectionPageBuilder_OrderCommunicationWay_Via {
            get {
                return ResourceManager.GetString("UiDirectionPageBuilder_OrderCommunicationWay_Via", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefijo.
        /// </summary>
        internal static string UiInvoicingBuilder_LoadAccounts_Prefijo {
            get {
                return ResourceManager.GetString("UiInvoicingBuilder_LoadAccounts_Prefijo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cta.Soportado.
        /// </summary>
        internal static string UiInvoicingBuilder_LoadIntraco_CtaSoportado {
            get {
                return ResourceManager.GetString("UiInvoicingBuilder_LoadIntraco_CtaSoportado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forma de Pago.
        /// </summary>
        internal static string UiInvoicingBuilder_LoadInvocingData_FormaDePago {
            get {
                return ResourceManager.GetString("UiInvoicingBuilder_LoadInvocingData_FormaDePago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuenta L/P.
        /// </summary>
        internal static string UiInvoicingBuilder_LoadLeasingUiObjects_CuentaLP {
            get {
                return ResourceManager.GetString("UiInvoicingBuilder_LoadLeasingUiObjects_CuentaLP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de alta.
        /// </summary>
        internal static string UiMiddlePartPageBuilder_BuildDates_FechaDeAlta {
            get {
                return ResourceManager.GetString("UiMiddlePartPageBuilder_BuildDates_FechaDeAlta", resourceCulture);
            }
        }
    }
}
