//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KarveCar.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("es-ES")]
        public string Language {
            get {
                return ((string)(this["Language"]));
            }
            set {
                this["Language"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Dsn=DBRENT_NET16;uid=cv;pwd=1929")]
        public string CadenaConexion {
            get {
                return ((string)(this["CadenaConexion"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("rgrMaestrosCentrosAlquiler")]
        public string rbtbMaestros0 {
            get {
                return ((string)(this["rbtbMaestros0"]));
            }
            set {
                this["rbtbMaestros0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("rgrMaestrosClientes")]
        public string rbtbMaestros1 {
            get {
                return ((string)(this["rbtbMaestros1"]));
            }
            set {
                this["rbtbMaestros1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("rgrMaestrosComisionistas")]
        public string rbtbMaestros2 {
            get {
                return ((string)(this["rbtbMaestros2"]));
            }
            set {
                this["rbtbMaestros2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("rgrMaestrosContratos")]
        public string rbtbMaestros3 {
            get {
                return ((string)(this["rbtbMaestros3"]));
            }
            set {
                this["rbtbMaestros3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("rgrMaestrosIncidencias")]
        public string rbtbMaestros4 {
            get {
                return ((string)(this["rbtbMaestros4"]));
            }
            set {
                this["rbtbMaestros4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("rgrMaestrosProveedores")]
        public string rbtbMaestros5 {
            get {
                return ((string)(this["rbtbMaestros5"]));
            }
            set {
                this["rbtbMaestros5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("rgrMaestrosReservas")]
        public string rbtbMaestros6 {
            get {
                return ((string)(this["rbtbMaestros6"]));
            }
            set {
                this["rbtbMaestros6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("rgrContratos")]
        public string rbtbContratos0 {
            get {
                return ((string)(this["rbtbContratos0"]));
            }
            set {
                this["rbtbContratos0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("rgrCambiosContratos")]
        public string rbtbContratos1 {
            get {
                return ((string)(this["rbtbContratos1"]));
            }
            set {
                this["rbtbContratos1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("rgrVariosContratos")]
        public string rbtbContratos2 {
            get {
                return ((string)(this["rbtbContratos2"]));
            }
            set {
                this["rbtbContratos2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("rgrReservas")]
        public string rbtbReservas0 {
            get {
                return ((string)(this["rbtbReservas0"]));
            }
            set {
                this["rbtbReservas0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("rgrAtipicos")]
        public string rbtbAtipicos0 {
            get {
                return ((string)(this["rbtbAtipicos0"]));
            }
            set {
                this["rbtbAtipicos0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("rgrComercial")]
        public string rbtbComercial0 {
            get {
                return ((string)(this["rbtbComercial0"]));
            }
            set {
                this["rbtbComercial0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("rgrFacturacion")]
        public string rbtbFacturacion0 {
            get {
                return ((string)(this["rbtbFacturacion0"]));
            }
            set {
                this["rbtbFacturacion0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("rgrRecibosCartera")]
        public string rbtbFacturacion1 {
            get {
                return ((string)(this["rbtbFacturacion1"]));
            }
            set {
                this["rbtbFacturacion1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("rgrRemesas")]
        public string rbtbFacturacion2 {
            get {
                return ((string)(this["rbtbFacturacion2"]));
            }
            set {
                this["rbtbFacturacion2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("rgrEnlacesContables")]
        public string rbtbFacturacion3 {
            get {
                return ((string)(this["rbtbFacturacion3"]));
            }
            set {
                this["rbtbFacturacion3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("rgrExportacion")]
        public string rbtbFacturacion4 {
            get {
                return ((string)(this["rbtbFacturacion4"]));
            }
            set {
                this["rbtbFacturacion4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("rgrImpresion")]
        public string rbtbFacturacion5 {
            get {
                return ((string)(this["rbtbFacturacion5"]));
            }
            set {
                this["rbtbFacturacion5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("rgrEstadisticasFacturas")]
        public string rbtbFacturacion6 {
            get {
                return ((string)(this["rbtbFacturacion6"]));
            }
            set {
                this["rbtbFacturacion6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("rgrInmovilizaciones")]
        public string rbtbFlota0 {
            get {
                return ((string)(this["rbtbFlota0"]));
            }
            set {
                this["rbtbFlota0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("rgrUtilidades")]
        public string rbtbFlota1 {
            get {
                return ((string)(this["rbtbFlota1"]));
            }
            set {
                this["rbtbFlota1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("rgrVariosFlota")]
        public string rbtbFlota2 {
            get {
                return ((string)(this["rbtbFlota2"]));
            }
            set {
                this["rbtbFlota2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("rgrIncidencias")]
        public string rbtbIncidencias0 {
            get {
                return ((string)(this["rbtbIncidencias0"]));
            }
            set {
                this["rbtbIncidencias0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("rgrEstadisticas")]
        public string rbtbEstadisticas0 {
            get {
                return ((string)(this["rbtbEstadisticas0"]));
            }
            set {
                this["rbtbEstadisticas0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("rgrListados")]
        public string rbtbListados0 {
            get {
                return ((string)(this["rbtbListados0"]));
            }
            set {
                this["rbtbListados0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("rgrConfiguracion")]
        public string rbtbConfiguracion0 {
            get {
                return ((string)(this["rbtbConfiguracion0"]));
            }
            set {
                this["rbtbConfiguracion0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("rgrIdiomas")]
        public string rbtbConfiguracion1 {
            get {
                return ((string)(this["rbtbConfiguracion1"]));
            }
            set {
                this["rbtbConfiguracion1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("rgrPersonal")]
        public string rbtbConfiguracion2 {
            get {
                return ((string)(this["rbtbConfiguracion2"]));
            }
            set {
                this["rbtbConfiguracion2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("rgrUtilitarios")]
        public string rbtbConfiguracion3 {
            get {
                return ((string)(this["rbtbConfiguracion3"]));
            }
            set {
                this["rbtbConfiguracion3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("rgrVariosConfiguracion")]
        public string rbtbConfiguracion4 {
            get {
                return ((string)(this["rbtbConfiguracion4"]));
            }
            set {
                this["rbtbConfiguracion4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("rgrKarve")]
        public string rbtbConfiguracion5 {
            get {
                return ((string)(this["rbtbConfiguracion5"]));
            }
            set {
                this["rbtbConfiguracion5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("cv")]
        public string Usuario {
            get {
                return ((string)(this["Usuario"]));
            }
            set {
                this["Usuario"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("rgrMaestrosTarifas")]
        public string rbtbMaestros7 {
            get {
                return ((string)(this["rbtbMaestros7"]));
            }
            set {
                this["rbtbMaestros7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("rgrMaestrosVehiculos")]
        public string rbtbMaestros8 {
            get {
                return ((string)(this["rbtbMaestros8"]));
            }
            set {
                this["rbtbMaestros8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("rgrMaestrosVarios")]
        public string rbtbMaestros9 {
            get {
                return ((string)(this["rbtbMaestros9"]));
            }
            set {
                this["rbtbMaestros9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("rgrServicios")]
        public string rbtbServicios0 {
            get {
                return ((string)(this["rbtbServicios0"]));
            }
            set {
                this["rbtbServicios0"] = value;
            }
        }
    }
}
